### ISSUE TITLE
Methods\StaticRule

### ISSUE THREAD

**Issue by localheinz** [localheinz/phpstan-rules#133]
A `private` method that does not access any instance members of the containing class can be easily marked as `static`.

This has the following advantages:

- a developer can immediately see that the method does not access any instance membes
- a `static` method can be used in `static` closures, which means that by turning a non-`static` method into a `static` method, perhaps non-`static` closures can be marked as `static`

Also see #90.

**Comment by Slamdunk** [comment]
As pointed out in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4557#discussion_r326203184 this rule should be applied to Traits too.

A fixer can't fix them, read https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4557#discussion_r326501399, but a static analyzer can safely warn them too.
