### ISSUE TITLE
Exclude Doctrine Entities from the FinalRule

### ISSUE THREAD

**Issue by dmecke** [localheinz/phpstan-rules#78]
I would like to use the `FinalRule` and I've tried to write my own implementation before I stumbled over your package. Do you have any solution for the problem that doctrine entities must not be `final` because of their proxy classes? I understand that I can whitelist them one by one in your implementation, but that does not feel too clean as I have to adjust the config file of a CI tool every time I add something in my domain layer. I also don't put them into one huge `Entity` directory, so the location is no indication neither. Do you have any suggestions?

**Comment by localheinz** [comment]
@dmecke 

You might like #84!

**Comment by dmecke** [comment]
Indeed! Thanks a lot!
