### ISSUE TITLE
FinalMethodRule

### ISSUE THREAD

**Issue by Slamdunk** [localheinz/phpstan-rules#88]
Hi, following `FinalRule` for classes I would propose `FinalMethodRule` for public methods of abstract classes, see https://slamdunk.github.io/blog/when-to-declare-methods-final/

I have a [phpstan-extension package too](https://github.com/Slamdunk/phpstan-extensions) but yours is more focused on strictness, so such a rule would fit better here.

Would you consider a PR for this topic?

**Comment by Slamdunk** [comment]
Of course the rule would only be active with:
```
parameters:
	allowAbstractClasses: true
```

**Comment by localheinz** [comment]
Love it, great idea!

**Comment by Slamdunk** [comment]
Have I already spotted a use-case?
https://github.com/localheinz/phpstan-rules/blob/51d8c8ebc14ef4dec045db03de309aebd2097343/test/Integration/AbstractTestCase.php#L44
:smiley:

**Comment by Slamdunk** [comment]
Note to self: related PHP-CS-Fixer rule https://github.com/Slamdunk/php-cs-fixer-extensions/blob/v1.19.0/lib/FinalAbstractPublicFixer.php
